export var XP_EVENT_VALUE;
(function (XP_EVENT_VALUE) {
    XP_EVENT_VALUE[XP_EVENT_VALUE["TEXT_POST"] = 1] = "TEXT_POST";
    XP_EVENT_VALUE[XP_EVENT_VALUE["IMAGE_POST"] = 3] = "IMAGE_POST";
    XP_EVENT_VALUE[XP_EVENT_VALUE["NEWS_POST"] = 5] = "NEWS_POST";
    XP_EVENT_VALUE[XP_EVENT_VALUE["SOCIAL_CONNECT"] = 150] = "SOCIAL_CONNECT";
    XP_EVENT_VALUE[XP_EVENT_VALUE["ADD_COINS"] = 10] = "ADD_COINS";
})(XP_EVENT_VALUE || (XP_EVENT_VALUE = {}));
export class XP_Levels {
}
XP_Levels.level_targets = [
    0,
    1000,
    5000,
    15000,
    25000,
    50000,
    75000,
    100000,
    125000,
    150000
];
