DROP TABLE IF EXISTS public.games;

CREATE TABLE public.games (
	id integer primary key not null,
	age_ratings character varying,
	aggregated_rating decimal,
	aggregated_rating_count integer,
	alternative_names character varying,
	artworks character varying,
	bundles character varying,
	category integer,
	checksum character varying,
	collection integer,
	cover integer,
	created_at character varying,
	dlcs character varying,
	expanded_games character varying,
	expansions character varying,
	external_games character varying,
	first_release_date character varying,
	follows integer,
	forks character varying,
	franchise integer,
	franchises character varying,
	game_engines character varying,
	game_modes character varying,
	genres character varying,
	hypes integer,
	involved_companies character varying,
	keywords character varying,
	multiplayer_modes character varying,
	name character varying,
	parent_game character varying,
	platforms character varying,
	player_perspectives character varying,
	ports character varying,
	rating decimal,
	rating_count integer,
	release_dates character varying,
	remakes character varying,
	remasters character varying,
	screenshots character varying,
	similar_games character varying,
	slug character varying,
	standalone_expansions character varying,
	status character varying,
	storyline character varying,
	summary character varying,
	tags character varying,
	themes character varying,
	total_rating decimal,
	total_rating_count integer,
	updated_at timestamp without time zone,
	url character varying,
	version_parent character varying,
	version_title character varying,
	videos character varying,
	websites character varying
);